kind: Service
apiVersion: v1
metadata:
  name: petrolalert
spec:
  selector:
    app: petrolalert
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petrolalert
spec:
  selector:
    matchLabels:
      app: petrolalert
  replicas: 1
  template:
    metadata:
      labels:
        app: petrolalert
    spec:
      containers:
        - name: petrolalert
          image: petrolalert:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

